#Create secrets.yaml file with passwords
#api_pass: "<API PASS>"
#ota_pass: "<OTA PASS>"
#wifi_ssid: "<WIFI SSID>"
#wifi_pass: "<WIFI PASS>"

substitutions:
  device_name: esphome-test-snmp-esp32
  friendly_name: "SNMP ESP32 Test node"
  device_description: "For SNMP test purposes"

esphome:
  name: $device_name
  comment: ${device_description}
  platform: ESP32
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

captive_portal:

# Enable logging
#logger:
#  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

snmp:
  location: Cyberspace
  contact: John Doe

external_components:
  # SNMP component
  # - source: github://aquaticus/esphome-snmp
  - source:
      type: local
      path: ../esphome-snmp/components
