#Create secrets.yaml file with passwords
#api_pass: "<API PASS>"
#ota_pass: "<OTA PASS>"
#wifi_ssid: "<WIFI SSID>"
#wifi_pass: "<WIFI PASS>"

substitutions:
  device_name: esphome-test-snmp-esp8266
  friendly_name: "SNMP ESP8266 Test node"
  device_description: "For SNMP test purposes"

esphome:
  name: $device_name
  comment: ${device_description}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

captive_portal:

# Enable logging
#logger:
#  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

snmp:
  location: Cyberspace
  contact: John Doe
